spring.application.name=material-flow-rate-adjustment
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
jwt.password=${JWT_PASSWORD}
jwt.period=${JWT_PERIOD}
admin.user=${ADMIN_USER}
admin.password=${ADMIN_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate